import { type Locale } from "@/lib/localizedRoutes";

export type { Locale };

type LocalizedText = Record<Locale, string>;

export type GalleryCategory = {
  slug: string;
  cover: string;
  images: string[];
  captions: Record<Locale, string[]>;
  title: LocalizedText;
  intro: LocalizedText;
  hubTagline: LocalizedText;
};

const GENERAL_DIR = "/galeria/Ogolne";
const FILM_DIR = "/galeria/Sciezka_filmowa";
const EVENTS_DIR = "/galeria/Wydarzenia";
const OPENING_GALA_DIR = "/galeria/Gala_otwarcia";
const EXHIBITION_DIR = "/galeria/Wystawa/HarryPotter_TheExhibition";
const K360_DIR = "/galeria/K360";
const MARS_DIR = "/galeria/Projekt_MARS/webp";

const range = (n: number) => Array.from({ length: n }, (_, i) => i + 1);

const GENERAL_IMAGES = [
  `${GENERAL_DIR}/webp/1.webp`,
  `${GENERAL_DIR}/webp/kopuly_1.webp`,
  `${GENERAL_DIR}/webp/3.webp`,
  `${GENERAL_DIR}/webp/kopuly_7.webp`,
  `${GENERAL_DIR}/webp/kopuly_2.webp`,
  `${GENERAL_DIR}/webp/6.webp`,
  `${GENERAL_DIR}/webp/7.webp`,
  `${GENERAL_DIR}/webp/8.webp`,
];
const FILM_IMAGES = [
  "wejscie_korytarz_k9",
  "korytarz_k7",
  "era_niema",
  "era_analogowa_1",
  "era_analogowa_2",
  "era_cyfrowa_1",
  "era_cyfrowa_2",
  "era_cyfrowa_3",
  "K10_ozdoby",
  "K9_quizy",
  "k11_czerwony_dywan",
  "sciezka_1",
  "sciezka_2",
  "sciezka_3",
  "sciezka_4",
  "img_0426_focus",
].map((name) => `${FILM_DIR}/webp/${name}.webp`);
const EVENTS_IMAGES = range(8).map((n) => `${EVENTS_DIR}/webp/${n}.webp`);
const OPENING_GALA_IMAGES = range(12).map((n) => `${OPENING_GALA_DIR}/jpg/${n}.jpg`);
const HP_IMAGES = range(8).map((n) => `${EXHIBITION_DIR}/webp/${n}.webp`);
const K360_IMAGES = [
  `${K360_DIR}/1.webp`,
  `${K360_DIR}/2.webp`,
  `${K360_DIR}/3.webp`,
  `${K360_DIR}/4.webp`,
  `${K360_DIR}/K360_1.webp`,
  `${K360_DIR}/K360_2.webp`,
];
const MARS_IMAGES = range(7).map((n) => `${MARS_DIR}/MARS_${n}.webp`);

export const GALLERY_CATEGORIES: GalleryCategory[] = [
  {
    slug: "ogolne",
    cover: GENERAL_IMAGES[0],
    images: GENERAL_IMAGES,
    title: { pl: "Ogólne", en: "General", pt: "Geral", de: "Allgemein", zh: "综合" },
    intro: {
      pl: "Architektura, krajobraz i przestrzenie Alvernia Planet.",
      en: "Architecture, landscape and the spaces of Alvernia Planet.",
      pt: "Arquitetura, paisagem e espaços da Alvernia Planet.",
      de: "Architektur, Landschaft und die Räume von Alvernia Planet.",
      zh: "Alvernia Planet 的建筑、景观与空间。",
    },
    hubTagline: {
      pl: "Obiekt i otoczenie",
      en: "Venue and surroundings",
      pt: "Espaço e arredores",
      de: "Gelände und Umgebung",
      zh: "园区与周边",
    },
    captions: {
      pl: [
        "Kopuły z lotu ptaka",
        "Kopuły z bliska",
        "Korytarz kapsułowy",
        "Kopuły, kadr panoramiczny",
        "Kopuły, widok z perspektywy",
        "Przeszklony tunel wejściowy",
        "Domy kopułowe o zmierzchu",
        "Kompleks z drona",
      ],
      en: [
        "Domes from above",
        "Domes up close",
        "Capsule corridor",
        "Domes, panoramic frame",
        "Domes, perspective view",
        "Glass entry tunnel",
        "Domes at dusk",
        "Drone view of the complex",
      ],
      pt: [
        "Cúpulas vistas de cima",
        "Cúpulas em primeiro plano",
        "Corredor cápsula",
        "Cúpulas, vista panorâmica",
        "Cúpulas, vista em perspetiva",
        "Túnel de entrada envidraçado",
        "Cúpulas ao entardecer",
        "Vista do complexo por drone",
      ],
      de: [
        "Kuppeln von oben",
        "Kuppeln aus der Nähe",
        "Kapselkorridor",
        "Kuppeln, Panoramaaufnahme",
        "Kuppeln, perspektivische Ansicht",
        "Verglaster Eingangstunnel",
        "Kuppeln in der Dämmerung",
        "Der Komplex aus der Drohnenperspektive",
      ],
      zh: [
        "俯瞰穹顶",
        "近观穹顶",
        "胶囊走廊",
        "穹顶全景",
        "穹顶透视视角",
        "玻璃入口通道",
        "暮色中的穹顶",
        "无人机航拍园区",
      ],
    },
  },
  {
    slug: "k360",
    cover: K360_IMAGES[1],
    images: K360_IMAGES,
    title: {
      pl: "Kino 360",
      en: "K360 Cinema",
      pt: "Cinema K360",
      de: "Kino 360",
      zh: "Kino 360 影院",
    },
    intro: {
      pl: "Kadry z fulldome 360°, największej kopuły projekcyjnej w Europie.",
      en: "Frames from the 360° fulldome, Europe's largest projection dome.",
      pt: "Imagens da cúpula 360°, a maior cúpula de projeção da Europa.",
      de: "Aufnahmen aus dem 360°-Fulldome, der größten Projektionskuppel Europas.",
      zh: "来自 360° 全穹顶的画面——欧洲最大的投影穹顶。",
    },
    hubTagline: {
      pl: "Fulldome 360°",
      en: "360° fulldome",
      pt: "Cúpula 360°",
      de: "360°-Fulldome",
      zh: "360° 全穹顶",
    },
    captions: {
      pl: [
        "Światło i dźwięk otaczają widza",
        "Fulldome na całej kopule",
        "Obraz 360° wypełnia pole widzenia",
        "Surowa estetyka Marsa",
        "Wnętrze kopuły",
        "Pod kopułą",
      ],
      en: [
        "Light and sound surround the viewer",
        "Fulldome across the entire ceiling",
        "360° image fills the field of view",
        "The raw aesthetic of Mars",
        "Inside the dome",
        "Under the dome",
      ],
      pt: [
        "Luz e som envolvem o público",
        "Fulldome em toda a cúpula",
        "Imagem 360° preenche o campo de visão",
        "A estética crua de Marte",
        "Interior da cúpula",
        "Sob a cúpula",
      ],
      de: [
        "Licht und Klang umhüllen die Zuschauer",
        "Fulldome auf der gesamten Kuppel",
        "360°-Bild füllt das gesamte Blickfeld",
        "Die raue Ästhetik des Mars",
        "Im Inneren der Kuppel",
        "Unter der Kuppel",
      ],
      zh: [
        "光影与声音环绕观众",
        "全穹顶覆盖整个穹面",
        "360° 画面充满视野",
        "火星的粗粝美学",
        "穹顶内部",
        "穹顶之下",
      ],
    },
  },
  {
    slug: "projekt-mars",
    cover: MARS_IMAGES[0],
    images: MARS_IMAGES,
    title: { pl: "MARS", en: "MARS", pt: "MARS", de: "MARS", zh: "MARS" },
    intro: {
      pl: "Marsjański plan filmowy: scenografia, rekwizyty i kadry z misji.",
      en: "A Martian film set: props, scenography and frames from the mission.",
      pt: "O plano marciano: cenografia, adereços e cenas da missão.",
      de: "Ein Marsfilmset: Requisiten, Szenografie und Aufnahmen von der Mission.",
      zh: "火星片场：道具、布景与任务画面。",
    },
    hubTagline: {
      pl: "Plan filmowy",
      en: "Film set",
      pt: "Plano de filmagens",
      de: "Filmset",
      zh: "电影片场",
    },
    captions: {
      pl: [
        "Marsjański plan",
        "Wnętrze misji",
        "Stacja łączności",
        "Stacja wodna",
        "Powierzchnia Marsa",
        "Akcja na planie",
        "Kadr z filmu",
      ],
      en: [
        "Martian set",
        "Mission interior",
        "Communications station",
        "Water station",
        "Surface of Mars",
        "Action on set",
        "Frame from the film",
      ],
      pt: [
        "Plano marciano",
        "Interior da missão",
        "Estação de comunicações",
        "Estação de água",
        "Superfície de Marte",
        "Ação no set",
        "Imagem do filme",
      ],
      de: [
        "Marsianisches Set",
        "Innenraum der Mission",
        "Kommunikationsstation",
        "Wasserstation",
        "Marsoberfläche",
        "Action am Set",
        "Standbild aus dem Film",
      ],
      zh: [
        "火星场景",
        "任务舱内部",
        "通信站",
        "供水站",
        "火星表面",
        "片场实拍",
        "影片画面",
      ],
    },
  },
  {
    slug: "sciezka-filmowa",
    cover: `${FILM_DIR}/webp/wejscie_korytarz_k9.webp`,
    images: FILM_IMAGES,
    title: {
      pl: "Edukacyjna ścieżka filmowa",
      en: "Educational film path",
      pt: "Percurso educativo de cinema",
      de: "Pädagogischer Filmpfad",
      zh: "电影教育之路",
    },
    intro: {
      pl: "Trasa zwiedzania, od historii kina po pracę na planie filmowym.",
      en: "The visitor route, from the history of cinema to work on a film set.",
      pt: "Percurso de visita, da história do cinema ao trabalho em set.",
      de: "Der Rundgang, von der Geschichte des Kinos bis zur Arbeit am Filmset.",
      zh: "参观路线，从电影史一路走到片场工作。",
    },
    hubTagline: {
      pl: "Trasa zwiedzania",
      en: "Visitor route",
      pt: "Percurso da visita",
      de: "Rundgang",
      zh: "参观路线",
    },
    captions: {
      pl: [
        "Korytarz wejściowy",
        "Korytarz K7",
        "Era niema",
        "Era analogowa",
        "Era analogowa, detal",
        "Era cyfrowa",
        "Era cyfrowa, detal",
        "Era cyfrowa, finał",
        "Ozdoby i detale",
        "Strefa quizów",
        "Czerwony dywan K11",
        "Kadr ze ścieżki",
        "Kadr ze ścieżki",
        "Kadr ze ścieżki",
        "Kadr ze ścieżki",
        "Detal scenografii",
      ],
      en: [
        "Entrance corridor",
        "Corridor K7",
        "Silent era",
        "Analog era",
        "Analog era, detail",
        "Digital era",
        "Digital era, detail",
        "Digital era, finale",
        "Set details",
        "Quiz zone",
        "Red carpet K11",
        "Frame from the path",
        "Frame from the path",
        "Frame from the path",
        "Frame from the path",
        "Set detail",
      ],
      pt: [
        "Corredor de entrada",
        "Corredor K7",
        "Era muda",
        "Era analógica",
        "Era analógica, detalhe",
        "Era digital",
        "Era digital, detalhe",
        "Era digital, final",
        "Detalhes de cenário",
        "Zona de quiz",
        "Tapete vermelho K11",
        "Imagem do percurso",
        "Imagem do percurso",
        "Imagem do percurso",
        "Imagem do percurso",
        "Detalhe de cenário",
      ],
      de: [
        "Eingangskorridor",
        "Korridor K7",
        "Stummfilmära",
        "Analoge Ära",
        "Analoge Ära, Detail",
        "Digitale Ära",
        "Digitale Ära, Detail",
        "Digitale Ära, Finale",
        "Ausstattung und Details",
        "Quizbereich",
        "Roter Teppich K11",
        "Aufnahme vom Rundgang",
        "Aufnahme vom Rundgang",
        "Aufnahme vom Rundgang",
        "Aufnahme vom Rundgang",
        "Detail der Szenografie",
      ],
      zh: [
        "入口走廊",
        "K7 走廊",
        "默片时代",
        "胶片时代",
        "胶片时代，细节",
        "数字时代",
        "数字时代，细节",
        "数字时代，尾声",
        "布景细节",
        "问答区",
        "K11 红毯",
        "路线上的画面",
        "路线上的画面",
        "路线上的画面",
        "路线上的画面",
        "布景细部",
      ],
    },
  },
  {
    slug: "wydarzenia",
    cover: EVENTS_IMAGES[0],
    images: EVENTS_IMAGES,
    title: {
      pl: "Wydarzenia",
      en: "Events",
      pt: "Eventos",
      de: "Veranstaltungen",
      zh: "活动",
    },
    intro: {
      pl: "Konferencje, gale i premiery odbywające się w Alvernia Planet.",
      en: "Conferences, galas and premieres held at Alvernia Planet.",
      pt: "Conferências, galas e estreias realizadas na Alvernia Planet.",
      de: "Konferenzen, Galas und Premieren in Alvernia Planet.",
      zh: "在 Alvernia Planet 举办的会议、晚宴与首映活动。",
    },
    hubTagline: {
      pl: "Eventy w kopule",
      en: "Events in the dome",
      pt: "Eventos na cúpula",
      de: "Veranstaltungen in der Kuppel",
      zh: "穹顶里的活动",
    },
    captions: {
      pl: [
        "Konferencja w kopule",
        "Strefa networkingowa",
        "Bankiet w K9",
        "Gala w kopule",
        "Plan eventu i scena",
        "Catering live",
        "Strefa atrakcji na scenie",
        "Pokaz w kopule z autoshow",
      ],
      en: [
        "Conference in the dome",
        "Networking area",
        "Banquet in K9",
        "Gala in the dome",
        "Show plan & stage",
        "Live catering",
        "Attraction zone on stage",
        "Show in the dome with car reveal",
      ],
      pt: [
        "Conferência na cúpula",
        "Área de networking",
        "Banquete na K9",
        "Gala na cúpula",
        "Plano do evento e palco",
        "Catering ao vivo",
        "Zona de atrações no palco",
        "Show na cúpula com revelação de carro",
      ],
      de: [
        "Konferenz in der Kuppel",
        "Networking-Bereich",
        "Bankett in K9",
        "Gala in der Kuppel",
        "Veranstaltungsplan und Bühne",
        "Live-Catering",
        "Attraktionsbereich auf der Bühne",
        "Show in der Kuppel mit Autopräsentation",
      ],
      zh: [
        "穹顶中的会议",
        "交流洽谈区",
        "K9 宴会",
        "穹顶中的晚宴",
        "活动布局与舞台",
        "现场餐饮",
        "舞台上的体验区",
        "穹顶中的新车发布秀",
      ],
    },
  },
  {
    slug: "gala-otwarcia",
    cover: OPENING_GALA_IMAGES[0],
    images: OPENING_GALA_IMAGES,
    title: {
      pl: "Gala otwarcia Kina K360",
      en: "K360 Cinema opening gala",
      pt: "Gala de abertura da Cinema K360",
      de: "Eröffnungsgala des Kino 360",
      zh: "Kino 360 影院开幕晚宴",
    },
    intro: {
      pl: "Zdjęcia z oficjalnej gali otwarcia Kina K360 w Alvernia Planet.",
      en: "Photos from the official opening gala of the K360 Cinema at Alvernia Planet.",
      pt: "Fotografias da gala oficial de abertura da Cinema K360 na Alvernia Planet.",
      de: "Fotos von der offiziellen Eröffnungsgala des Kino 360 in Alvernia Planet.",
      zh: "Kino 360 影院在 Alvernia Planet 举行的正式开幕晚宴照片。",
    },
    hubTagline: {
      pl: "Premiera obiektu",
      en: "Venue premiere",
      pt: "Estreia do espaço",
      de: "Eröffnung des Standorts",
      zh: "园区首度亮相",
    },
    captions: {
      pl: [],
      en: [],
      pt: [],
      de: [],
      zh: [],
    },
  },
  {
    slug: "harry-potter",
    cover: HP_IMAGES[0],
    images: HP_IMAGES,
    title: {
      pl: "Harry Potter: The Exhibition",
      en: "Harry Potter: The Exhibition",
      pt: "Harry Potter: The Exhibition",
      de: "Harry Potter: The Exhibition",
      zh: "Harry Potter: The Exhibition",
    },
    intro: {
      pl: "Wystawa tematyczna 10.04 – 17.08.2025.",
      en: "Themed exhibition Apr 10 – Aug 17, 2025.",
      pt: "Exposição temática 10 Abr – 17 Ago 2025.",
      de: "Themenausstellung 10.04. – 17.08.2025.",
      zh: "主题展览 2025年4月10日 – 8月17日。",
    },
    hubTagline: {
      pl: "Wystawa tematyczna",
      en: "Themed exhibition",
      pt: "Exposição temática",
      de: "Themenausstellung",
      zh: "主题展览",
    },
    captions: {
      pl: [
        "Wejście do wystawy",
        "Knight Bus",
        "Początek trasy – portal",
        "Sala immersyjna z mapą",
        "Strefa rejestracji",
        "Galeria portretów",
        "Autobus wystawy na zewnątrz",
        "Spotkanie z gośćmi",
      ],
      en: [
        "Exhibition entry",
        "Knight Bus",
        "Route kickoff – portal",
        "Immersive map room",
        "Registration hall",
        "Portrait gallery",
        "Exhibition bus outside",
        "Guest meet & greet",
      ],
      pt: [
        "Entrada da exposição",
        "Knight Bus",
        "Início do percurso – portal",
        "Sala imersiva com mapa",
        "Sala de registo",
        "Galeria de retratos",
        "Autocarro da exposição no exterior",
        "Encontro com convidados",
      ],
      de: [
        "Eingang zur Ausstellung",
        "Knight Bus",
        "Beginn des Rundgangs – Portal",
        "Immersiver Kartenraum",
        "Empfangs- und Registrierungsbereich",
        "Porträtgalerie",
        "Ausstellungsbus im Außenbereich",
        "Meet & Greet mit Gästen",
      ],
      zh: [
        "展览入口",
        "Knight Bus",
        "参观起点——传送门",
        "沉浸式地图厅",
        "登记大厅",
        "肖像画廊",
        "室外的展览巴士",
        "与来宾见面会",
      ],
    },
  },
];

export function findCategoryBySlug(slug: string): GalleryCategory | undefined {
  return GALLERY_CATEGORIES.find((category) => category.slug === slug);
}

export const GALLERY_HUB_LABELS: Record<
  Locale,
  {
    tag: string;
    title: string;
    subtitle: string;
    backToHub: string;
    morePhotos: string;
    photoCountLabel: (count: number) => string;
    backToHubAria: string;
    loadingImage: string;
    imageError: string;
    photoLabel: string;
  }
> = {
  pl: {
    tag: "Galeria",
    title: "Galeria",
    subtitle:
      "Wybierz kategorię, żeby zobaczyć pełną kolekcję zdjęć.",
    backToHub: "Wróć do galerii",
    morePhotos: "Zobacz więcej",
    photoCountLabel: (count) =>
      count === 1 ? "1 zdjęcie" : count < 5 ? `${count} zdjęcia` : `${count} zdjęć`,
    backToHubAria: "Wróć do strony galerii",
    loadingImage: "Ładowanie zdjęcia...",
    imageError: "Nie udało się wczytać",
    photoLabel: "Zdjęcie",
  },
  en: {
    tag: "Gallery",
    title: "Gallery",
    subtitle: "Pick a category to browse the full set of photos.",
    backToHub: "Back to gallery",
    morePhotos: "See more",
    photoCountLabel: (count) => `${count} ${count === 1 ? "photo" : "photos"}`,
    backToHubAria: "Back to the gallery page",
    loadingImage: "Loading image...",
    imageError: "Failed to load",
    photoLabel: "Photo",
  },
  pt: {
    tag: "Galeria",
    title: "Galeria",
    subtitle: "Escolhe uma categoria para ver toda a coleção de fotos.",
    backToHub: "Voltar à galeria",
    morePhotos: "Ver mais",
    photoCountLabel: (count) => `${count} ${count === 1 ? "foto" : "fotos"}`,
    backToHubAria: "Voltar à página da galeria",
    loadingImage: "A carregar foto...",
    imageError: "Falha ao carregar",
    photoLabel: "Foto",
  },
  de: {
    tag: "Galerie",
    title: "Galerie",
    subtitle: "Wählen Sie eine Kategorie, um die gesamte Fotosammlung zu sehen.",
    backToHub: "Zurück zur Galerie",
    morePhotos: "Mehr ansehen",
    photoCountLabel: (count) => `${count} ${count === 1 ? "Foto" : "Fotos"}`,
    backToHubAria: "Zurück zur Galerieseite",
    loadingImage: "Bild wird geladen...",
    imageError: "Laden fehlgeschlagen",
    photoLabel: "Foto",
  },
  zh: {
    tag: "图库",
    title: "图库",
    subtitle: "选择一个分类，浏览全部照片。",
    backToHub: "返回图库",
    morePhotos: "查看更多",
    photoCountLabel: (count) => `${count} 张照片`,
    backToHubAria: "返回图库页面",
    loadingImage: "图片加载中……",
    imageError: "加载失败",
    photoLabel: "照片",
  },
};
